const Promise = require('bluebird');
const db = require('./db');

const { User, Crop } = require('./models');

const users = [
  {
    firstName: 'Chris',
    lastName: 'User',
    email: 'cqlanus@gmail.com',
    password: 'hello123'
  },
  {
    firstName: 'Chris',
    lastName: 'admin',
    email: 'cqlanus+01@gmail.com',
    password: 'password123',
    isAdmin: true
  },
  {
    firstName: 'Shannon',
    lastName: 'User',
    email: 'cqlanus+02@gmail.com',
    password: 'abc123'
  }
];

const crops = [
  {
    commonName            : 'Arugula',
    latinName             : 'Eruca sativa',
    family                : 'Cabbage',
    seedDepth             : .25,
    minGermTemp           : 40,
    maxGermTemp           : 55,
    minGermTime           : 5,
    maxGermTime           : 7,
    sowIndoors            : 8,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 50,
    maxGrowTemp           : 65,
    seedSpacing           : 1,
    thinTo                : 6,
    rowSpacing            : 6,
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Beans (bush)',
    latinName             : 'Phaseolus vulgaris',
    family                : 'Pea',
    seedDepth             : 1.0,
    minGermTemp           : 75,
    maxGermTemp           : 85,
    minGermTime           : 7,
    maxGermTime           : 10,
    sowIndoors            : 0,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 4,
    rowSpacing            : 8,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 10,
    maxFlowerToHarvestTime: 14,
  },
  {
    commonName            : 'Beans (fava)',
    latinName             : 'Vicia faba',
    family                : 'Pea',
    seedDepth             : 1.0,
    minGermTemp           : 55,
    maxGermTemp           : 75,
    minGermTime           : 7,
    maxGermTime           : 10,
    sowIndoors            : 0,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 4,
    rowSpacing            : 8,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 10,
    maxFlowerToHarvestTime: 14,
  },
  {
    commonName            : 'Beans (pole)',
    latinName             : 'Phaseolus vulgaris',
    family                : 'Pea',
    seedDepth             : 1,
    minGermTemp           : 65,
    maxGermTemp           : 85,
    minGermTime           : 7,
    maxGermTime           : 10,
    sowIndoors            : 0,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 3,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 10,
    maxFlowerToHarvestTime: 14,
  },
  {
    commonName            : 'Beets',
    latinName             : 'Beta vulgaris',
    family                : 'Beet',
    seedDepth             : 0.5,
    minGermTemp           : 75,
    maxGermTemp           : 85,
    minGermTime           : 5,
    maxGermTime           : 5,
    sowIndoors            : 5,
    sowOutdoors           : 4,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.5,
    minGrowTemp           : 65,
    maxGrowTemp           : 75,
    seedSpacing           : 3,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Broccoli',
    latinName             : 'Brassica olerecea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 68,
    maxGermTemp           : 85,
    minGermTime           : 4,
    maxGermTime           : 7,
    sowIndoors            : 8,
    sowOutdoors           : 16,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 16,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Brussels Sprouts',
    latinName             : 'Brassica olerecea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 75,
    maxGermTemp           : 85,
    minGermTime           : 5,
    maxGermTime           : 8,
    sowIndoors            : 6,
    sowOutdoors           : 16,
    minSoilPh             : 6.0,
    maxSoilPh             : 6.8,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 16,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Cabbage',
    latinName             : 'Brassica olerecea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 75,
    maxGermTemp           : 85,
    minGermTime           : 5,
    maxGermTime           : 5,
    sowIndoors            : 6,
    sowOutdoors           : 12,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 12,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Carrot',
    latinName             : 'Daucus carota',
    family                : 'Carrot',
    seedDepth             : 0.25,
    minGermTemp           : 75,
    minGermTime           : 6,
    maxGermTime           : 6,
    sowIndoors            : 0,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 70,
    seedSpacing           : 2,
    rowSpacing            : 9,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Cauliflower',
    latinName             : 'Brassica olerecea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 80,
    minGermTime           : 6,
    maxGermTime           : 6,
    sowIndoors            : 6,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 70,
    seedSpacing           : 15,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Celery',
    latinName             : 'Apium graveolens',
    family                : 'Carrot',
    seedDepth             : 0,
    minGermTemp           : 70,
    minGermTime           : 7,
    sowIndoors            : 10,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 70,
    seedSpacing           : 8,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Corn',
    latinName             : 'Zea mays',
    family                : 'Grass',
    seedDepth             : 1.0,
    minGermTemp           : 80,
    minGermTime           : 4,
    sowIndoors            : 0,
    sowOutdoors           : -1,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 65,
    maxGrowTemp           : 75,
    seedSpacing           : 8,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 18,
    maxFlowerToHarvestTime: 21,
  },
  {
    commonName            : 'Cucumber',
    latinName             : 'Cucumis sativus',
    family                : 'Cucumber',
    seedDepth             : 0.5,
    minGermTemp           : 80,
    maxGermTemp           : 95,
    minGermTime           : 3,
    maxGermTime           : 4,
    sowIndoors            : 3,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 70,
    maxGrowTemp           : 80,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 8,
    maxFlowerToHarvestTime: 10,
  },
  {
    commonName            : 'Eggplant',
    latinName             : 'Solanum melongena',
    family                : 'Tomato',
    seedDepth             : 0.25,
    minGermTemp           : 85,
    minGermTime           : 7,
    sowIndoors            : 6,
    minSoilPh             : 5.5,
    maxSoilPh             : 7.0,
    minGrowTemp           : 80,
    maxGrowTemp           : 90,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 40,
    maxFlowerToHarvestTime: 50,
  },
  {
    commonName            : 'Garlic',
    latinName             : 'Allium sativum',
    family                : 'Onion',
    seedDepth             : 2,
    minGermTemp           : 55,
    minGermTime           : 0,
    sowOutdoors           : 6,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 55,
    maxGrowTemp           : 75,
    seedSpacing           : 6,
    lightFreq             : 'full',
    waterFreq             : 'low',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Kale',
    latinName             : 'Brassica olerecea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 45,
    maxGermTemp           : 95,
    minGermTime           : 5,
    maxGermTime           : 7,
    sowIndoors            : 6,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 16,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Leeks',
    latinName             : 'Allium ampeloprasum',
    family                : 'Onion',
    seedDepth             : 0.25,
    minGermTemp           : 75,
    minGermTime           : 5,
    maxGermTime           : 7,
    sowIndoors            : 4,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    seedSpacing           : 6,
    rowSpacing            : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Lettuce (leaf)',
    latinName             : 'Lactuca sativa',
    family                : 'Sunflower',
    seedDepth             : 0.25,
    minGermTemp           : 40,
    maxGermTemp           : 60,
    minGermTime           : 7,
    maxGermTime           : 14,
    sowIndoors            : 4,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.0,
    minGrowTemp           : 55,
    maxGrowTemp           : 65,
    seedSpacing           : 1,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Lettuce (head)',
    latinName             : 'Lactuca sativa',
    family                : 'Sunflower',
    seedDepth             : 0.25,
    minGermTemp           : 40,
    maxGermTemp           : 60,
    minGermTime           : 7,
    maxGermTime           : 14,
    sowIndoors            : 4,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.0,
    minGrowTemp           : 55,
    maxGrowTemp           : 65,
    seedSpacing           : 10,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Melon',
    latinName             : 'Cucumis melo',
    family                : 'Cucumber',
    seedDepth             : 0.5,
    minGermTemp           : 80,
    maxGermTemp           : 90,
    minGermTime           : 3,
    maxGermTime           : 5,
    sowIndoors            : 3,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 70,
    maxGrowTemp           : 85,
    seedSpacing           : 16,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 40,
    maxFlowerToHarvestTime: 50,
  },
  {
    commonName            : 'Mustard',
    latinName             : 'Brassica juncea',
    family                : 'Cabbage',
    seedDepth             : 0.25,
    minGermTemp           : 65,
    maxGermTemp           : 70,
    minGermTime           : 4,
    maxGermTime           : 6,
    sowIndoors            : 2,
    minSoilPh             : 5.5,
    maxSoilPh             : 7.0,
    minGrowTemp           : 50,
    maxGrowTemp           : 60,
    seedSpacing           : 6,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Okra',
    latinName             : 'Abelmoschus esculentus',
    family                : 'Mallow',
    seedDepth             : 0.75,
    minGermTemp           : 80,
    maxGermTemp           : 95,
    minGermTime           : 5,
    maxGermTime           : 14,
    sowIndoors            : 5,
    minSoilPh             : 6.0,
    maxSoilPh             : 8.0,
    minGrowTemp           : 70,
    maxGrowTemp           : 90,
    seedSpacing           : 12,
    lightFreq             : 'full',
    waterFreq             : 'low',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Onion',
    latinName             : 'Allium cepa',
    family                : 'Onion',
    seedDepth             : 0.5,
    minGermTemp           : 65,
    maxGermTemp           : 85,
    minGermTime           : 4,
    maxGermTime           : 5,
    sowIndoors            : 8,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.5,
    minGrowTemp           : 55,
    maxGrowTemp           : 75,
    seedSpacing           : 3,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Parsnips',
    latinName             : 'Pastinaca sativa',
    family                : 'Carrot',
    seedDepth             : 0.5,
    minGermTemp           : 65,
    maxGermTemp           : 75,
    minGermTime           : 12,
    maxGermTime           : 14,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 4,
    rowSpacing            : 4,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'low',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Peas',
    latinName             : 'Pisum sativum',
    family                : 'Pea',
    seedDepth             : 1,
    minGermTemp           : 40,
    maxGermTemp           : 75,
    minGermTime           : 14,
    sowOutdoors           : 10,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 1,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
    minFlowerToHarvestTime: 8,
    maxFlowerToHarvestTime: 10,
  },
  {
    commonName            : 'Peppers',
    latinName             : 'Capsicum annuum',
    family                : 'Tomato',
    seedDepth             : 0.25,
    minGermTemp           : 80,
    maxGermTemp           : 85,
    minGermTime           : 6,
    maxGermTime           : 8,
    sowIndoors            : 8,
    minSoilPh             : 5.5,
    maxSoilPh             : 7.0,
    minGrowTemp           : 70,
    maxGrowTemp           : 85,
    seedSpacing           : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 40,
    maxFlowerToHarvestTime: 50,
  },
  {
    commonName            : 'Potatoes',
    latinName             : 'Solanum tuberosum',
    family                : 'Tomato',
    seedDepth             : 4,
    minGermTemp           : 45,
    minGermTime           : 0,
    sowIndoors            : 3,
    minSoilPh             : 5.0,
    maxSoilPh             : 6.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
  },
  {
    commonName            : 'Pumpkins',
    latinName             : 'Cucurbita pepo',
    family                : 'Cucumber',
    seedDepth             : 1,
    minGermTemp           : 70,
    maxGermTemp           : 90,
    minGermTime           : 6,
    maxGermTime           : 10,
    sowIndoors            : 4,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.5,
    minGrowTemp           : 65,
    maxGrowTemp           : 75,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 40,
    maxFlowerToHarvestTime: 60,
  },
  {
    commonName            : 'Radishes',
    latinName             : 'Raphanus sativus',
    family                : 'Cabbage',
    seedDepth             : 0.5,
    minGermTemp           : 45,
    maxGermTemp           : 90,
    minGermTime           : 4,
    maxGermTime           : 12,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 1,
    thinTo                : 4,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Rhubarb',
    latinName             : 'Rheum x culturoum',
    family                : 'Buckwheat',
    seedDepth             : 3.0,
    minGermTemp           : 40,
    maxGermTemp           : 60,
    minGermTime           : 0,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.5,
    minGrowTemp           : 40,
    maxGrowTemp           : 6.5,
    seedSpacing           : 24,
    lightFreq             : 'part',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Rutabaga',
    latinName             : 'Brassica napus',
    family                : 'Cabbage',
    seedDepth             : 0.5,
    minGermTemp           : 60,
    maxGermTemp           : 85,
    minGermTime           : 3,
    maxGermTime           : 5,
    minSoilPh             : 6.4,
    maxSoilPh             : 7.2,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 8,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
    {
    commonName            : 'Spinach',
    latinName             : 'Spinacia oleracea',
    family                : 'Beet',
    seedDepth             : 0.5,
    minGermTemp           : 50,
    maxGermTemp           : 75,
    minGermTime           : 7,
    maxGermTime           : 14,
    sowIndoors            : 4,
    minSoilPh             : 6.5,
    maxSoilPh             : 7.5,
    minGrowTemp           : 60,
    maxGrowTemp           : 65,
    seedSpacing           : 12,
    lightFreq             : 'full',
    waterFreq             : 'low',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    },
    {
    commonName            : 'Squash (summer)',
    latinName             : 'Cucurbita pepo',
    family                : 'Cucumber',
    seedDepth             : 1.0,
    minGermTemp           : 70,
    maxGermTemp           : 95,
    minGermTime           : 6,
    maxGermTime           : 10,
    sowIndoors            : 4,
    minSoilPh             : 6.0,
    maxSoilPh             : 6.5,
    minGrowTemp           : 65,
    maxGrowTemp           : 75,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 4,
    maxFlowerToHarvestTime: 5,
    },
    {
    commonName            : 'Squash (winter)',
    latinName             : 'Cucurbita spp.',
    family                : 'Cucumber',
    seedDepth             : 1.0,
    minGermTemp           : 70,
    maxGermTemp           : 90,
    minGermTime           : 6,
    maxGermTime           : 10,
    sowIndoors            : 4,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.5,
    minGrowTemp           : 65,
    maxGrowTemp           : 75,
    seedSpacing           : 18,
    lightFreq             : 'part',
    waterFreq             : 'high',
    nitrogenReq           : 'high',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 40,
    maxFlowerToHarvestTime: 60,
    },
    {
    commonName            : 'Strawberries',
    latinName             : 'Fragaria spp.',
    family                : 'Rose',
    seedDepth             : 0,
    minGermTemp           : 40,
    maxGermTemp           : 60,
    minGermTime           : 0,
    minSoilPh             : 6.0,
    maxSoilPh             : 6.8,
    minGrowTemp           : 60,
    maxGrowTemp           : 80,
    seedSpacing           : 12,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'med',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Sweet Potatoes',
    latinName             : 'Ipomoea batatas',
    family                : 'Morning glory',
    seedDepth             : 0,
    minGermTemp           : 0,
    minGermTime           : 0,
    sowOutdoors           : -2,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.5,
    minGrowTemp           : 65,
    maxGrowTemp           : 90,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'low',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Swiss Chard',
    latinName             : 'Beta vulgaris',
    family                : 'Beet',
    seedDepth             : 0.5,
    minGermTemp           : 50,
    maxGermTemp           : 85,
    minGermTime           : 5,
    maxGermTime           : 7,
    sowIndoors            : 2,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 50,
    maxGrowTemp           : 70,
    seedSpacing           : 8,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
  },
  {
    commonName            : 'Tomatillos',
    latinName             : 'Physalis ixocarpa',
    family                : 'Tomato',
    seedDepth             : 0.25,
    minGermTemp           : 70,
    maxGermTemp           : 80,
    minGermTime           : 7,
    maxGermTime           : 14,
    sowIndoors            : 4,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 60,
    maxGrowTemp           : 80,
    seedSpacing           : 3,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Tomatoes',
    latinName             : 'Lycoperscium esculentum',
    family                : 'Tomato',
    seedDepth             : 0.5,
    minGermTemp           : 80,
    minGermTime           : 6,
    maxGermTime           : 8,
    sowIndoors            : 6,
    minSoilPh             : 5.8,
    maxSoilPh             : 7.0,
    minGrowTemp           : 70,
    seedSpacing           : 15,
    lightFreq             : 'full',
    waterFreq             : 'high',
    nitrogenReq           : 'med',
    phosphorusReq         : 'high',
    potassiumReq          : 'high',
    minFlowerToHarvestTime: 45,
    maxFlowerToHarvestTime: 50,
  },
  {
    commonName            : 'Turnips',
    latinName             : 'Brassica rapa',
    family                : 'Cabbage',
    seedDepth             : 0.5,
    minGermTemp           : 50,
    maxGermTemp           : 95,
    minGermTime           : 2,
    maxGermTime           : 5,
    minSoilPh             : 5.5,
    maxSoilPh             : 6.8,
    minGrowTemp           : 40,
    maxGrowTemp           : 75,
    seedSpacing           : 1,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'low',
    phosphorusReq         : 'low',
    potassiumReq          : 'low',
  },
  {
    commonName            : 'Watermelon',
    latinName             : 'Citrullus lanatus',
    family                : 'Cucumber',
    seedDepth             : 0.5,
    minGermTemp           : 80,
    maxGermTemp           : 90,
    minGermTime           : 3,
    maxGermTime           : 10,
    sowIndoors            : 3,
    minSoilPh             : 6.0,
    maxSoilPh             : 7.0,
    minGrowTemp           : 70,
    maxGrowTemp           : 85,
    seedSpacing           : 18,
    lightFreq             : 'full',
    waterFreq             : 'med',
    nitrogenReq           : 'high',
    phosphorusReq         : 'med',
    potassiumReq          : 'med',
    minFlowerToHarvestTime: 45,
    maxFlowerToHarvestTime: 60,
  },
];

db.sync({ force: true })
  .then(() => {
    console.log('old data dropped, now inserting users');
    return Promise.map(users, user => User.create(user));
  })
  .then(() => {
    console.log('users created, now inserting crops');
    return Promise.map(crops, crop => Crop.create(crop));
  })
  .catch(err => console.error('problem', err))
  .finally(() => db.close());
